// GENERATED by tools/gen_offsets.py from SMO 1.0.0 (build 3CA12DFAAF9C82DA064D1698DF79CDA1). Do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace moonrush::offsets {

constexpr const char* kBuildId = "3CA12DFAAF9C82DA064D1698DF79CDA1";

// Offsets into the main module.
constexpr uintptr_t PlayerActorHakoniwa_movement = 0x41dd34;  // _ZN19PlayerActorHakoniwa8movementEv
constexpr uintptr_t GameDataFunction_getTotalShineNum = 0x528a64;  // _ZN16GameDataFunction16getTotalShineNumE22GameDataHolderAccessori
constexpr uintptr_t GameDataFunction_getCurrentShineNum = 0x5289a4;  // _ZN16GameDataFunction18getCurrentShineNumE22GameDataHolderAccessor
constexpr uintptr_t al_getSceneObj = 0x9cf008;  // _ZN2al11getSceneObjEPKNS_18IUseSceneObjHolderEi

// Object layout (verified in disassembly).
constexpr size_t PlayerActorHakoniwa_mConst = 0x130;
constexpr size_t LiveActor_IUseSceneObjHolder = 0x20;
constexpr int SceneObjId_GameDataHolder = 18;
constexpr size_t PlayerConst_size = 0x9a8;

// offset: field inside PlayerConst. getter: the 8-byte `ldr s0, [x0, #offset]; ret` function Moonrush hooks.
struct Field { const char* name; uint16_t offset; uintptr_t getter; };

constexpr Field k_walk[] = {
    {"NormalMinSpeed", 0xf0, 0x43d04c},
    {"NormalMaxSpeed", 0xec, 0x43d044},
    {"RunAfterTurnSpeedMax", 0x10c, 0x43d084},
    {"DashJudgeSpeed", 0x100, 0x43d06c},
};
constexpr Field k_squat[] = {
    {"SquatWalkSpeed", 0x5f8, 0x43da5c},
};
constexpr Field k_dive[] = {
    {"HeadSlidingSpeed", 0x62c, 0x43dac4},
    {"HeadSlidingSpeedMin", 0x630, 0x43dacc},
};
constexpr Field k_roll[] = {
    {"SlopeRollingSpeedStart", 0x27c, 0x43d364},
    {"SlopeRollingSpeedBoost", 0x280, 0x43d36c},
    {"SlopeRollingMaxSpeed", 0x284, 0x43d374},
    {"SlopeRollingReStartMaxAdd", 0x2c8, 0x43d3fc},
};
constexpr Field k_long_jump[] = {
    {"LongJumpInitSpeed", 0x42c, 0x43d6c4},
    {"LongJumpSpeed", 0x430, 0x43d6cc},
    {"LongJumpSpeedMin", 0x434, 0x43d6d4},
};
constexpr Field k_air[] = {
    {"JumpBaseSpeedMax", 0x2fc, 0x43d464},
    {"JumpMoveSpeedMin", 0x300, 0x43d46c},
    {"JumpMoveSpeedMax", 0x304, 0x43d474},
};
constexpr Field k_swim[] = {
    {"SwimSurfaceSpeedMaxH", 0x6c4, 0x43dbf4},
    {"SwimHighSpeedMaxH", 0x670, 0x43db4c},
    {"SwimLowSpeedMaxH", 0x678, 0x43db5c},
    {"SwimFloorSpeedMaxH", 0x668, 0x43db3c},
    {"SwimWalkMaxSpeed", 0x694, 0x43db94},
};

struct Getter { int group; const char* name; uint16_t field; uintptr_t offset; };
constexpr Getter k_getters[] = {
    {0, "NormalMinSpeed", 0xf0, 0x43d04c},  // walk
    {0, "NormalMaxSpeed", 0xec, 0x43d044},  // walk
    {0, "RunAfterTurnSpeedMax", 0x10c, 0x43d084},  // walk
    {0, "DashJudgeSpeed", 0x100, 0x43d06c},  // walk
    {1, "SquatWalkSpeed", 0x5f8, 0x43da5c},  // squat
    {2, "HeadSlidingSpeed", 0x62c, 0x43dac4},  // dive
    {2, "HeadSlidingSpeedMin", 0x630, 0x43dacc},  // dive
    {3, "SlopeRollingSpeedStart", 0x27c, 0x43d364},  // roll
    {3, "SlopeRollingSpeedBoost", 0x280, 0x43d36c},  // roll
    {3, "SlopeRollingMaxSpeed", 0x284, 0x43d374},  // roll
    {3, "SlopeRollingReStartMaxAdd", 0x2c8, 0x43d3fc},  // roll
    {4, "LongJumpInitSpeed", 0x42c, 0x43d6c4},  // long_jump
    {4, "LongJumpSpeed", 0x430, 0x43d6cc},  // long_jump
    {4, "LongJumpSpeedMin", 0x434, 0x43d6d4},  // long_jump
    {5, "JumpBaseSpeedMax", 0x2fc, 0x43d464},  // air
    {5, "JumpMoveSpeedMin", 0x300, 0x43d46c},  // air
    {5, "JumpMoveSpeedMax", 0x304, 0x43d474},  // air
    {6, "SwimSurfaceSpeedMaxH", 0x6c4, 0x43dbf4},  // swim
    {6, "SwimHighSpeedMaxH", 0x670, 0x43db4c},  // swim
    {6, "SwimLowSpeedMaxH", 0x678, 0x43db5c},  // swim
    {6, "SwimFloorSpeedMaxH", 0x668, 0x43db3c},  // swim
    {6, "SwimWalkMaxSpeed", 0x694, 0x43db94},  // swim
};

struct Signature { uintptr_t offset; uint32_t words[4]; uint8_t count; bool hookable; const char* what; };
constexpr Signature k_signatures[] = {
    {0x41dd34, {0xd105c3ff, 0x6d0d3bef, 0x6d0e33ed, 0x6d0f2beb}, 4, false, "PlayerActorHakoniwa_movement"},
    {0x528a64, {0x3100043f, 0x540000c0, 0xa9bf7bfd, 0x910003fd}, 4, false, "GameDataFunction_getTotalShineNum"},
    {0x5289a4, {0xf81c0ff7, 0xa90157f6, 0xa9024ff4, 0xa9037bfd}, 4, false, "GameDataFunction_getCurrentShineNum"},
    {0x9cf008, {0xf81e0ff3, 0xa9017bfd, 0x910043fd, 0xf9400008}, 4, false, "al_getSceneObj"},
    {0x43d04c, {0xbd40f000, 0xd65f03c0}, 2, true, "getNormalMinSpeed"},
    {0x43d044, {0xbd40ec00, 0xd65f03c0}, 2, true, "getNormalMaxSpeed"},
    {0x43d084, {0xbd410c00, 0xd65f03c0}, 2, true, "getRunAfterTurnSpeedMax"},
    {0x43d06c, {0xbd410000, 0xd65f03c0}, 2, true, "getDashJudgeSpeed"},
    {0x43da5c, {0xbd45f800, 0xd65f03c0}, 2, true, "getSquatWalkSpeed"},
    {0x43dac4, {0xbd462c00, 0xd65f03c0}, 2, true, "getHeadSlidingSpeed"},
    {0x43dacc, {0xbd463000, 0xd65f03c0}, 2, true, "getHeadSlidingSpeedMin"},
    {0x43d364, {0xbd427c00, 0xd65f03c0}, 2, true, "getSlopeRollingSpeedStart"},
    {0x43d36c, {0xbd428000, 0xd65f03c0}, 2, true, "getSlopeRollingSpeedBoost"},
    {0x43d374, {0xbd428400, 0xd65f03c0}, 2, true, "getSlopeRollingMaxSpeed"},
    {0x43d3fc, {0xbd42c800, 0xd65f03c0}, 2, true, "getSlopeRollingReStartMaxAdd"},
    {0x43d6c4, {0xbd442c00, 0xd65f03c0}, 2, true, "getLongJumpInitSpeed"},
    {0x43d6cc, {0xbd443000, 0xd65f03c0}, 2, true, "getLongJumpSpeed"},
    {0x43d6d4, {0xbd443400, 0xd65f03c0}, 2, true, "getLongJumpSpeedMin"},
    {0x43d464, {0xbd42fc00, 0xd65f03c0}, 2, true, "getJumpBaseSpeedMax"},
    {0x43d46c, {0xbd430000, 0xd65f03c0}, 2, true, "getJumpMoveSpeedMin"},
    {0x43d474, {0xbd430400, 0xd65f03c0}, 2, true, "getJumpMoveSpeedMax"},
    {0x43dbf4, {0xbd46c400, 0xd65f03c0}, 2, true, "getSwimSurfaceSpeedMaxH"},
    {0x43db4c, {0xbd467000, 0xd65f03c0}, 2, true, "getSwimHighSpeedMaxH"},
    {0x43db5c, {0xbd467800, 0xd65f03c0}, 2, true, "getSwimLowSpeedMaxH"},
    {0x43db3c, {0xbd466800, 0xd65f03c0}, 2, true, "getSwimFloorSpeedMaxH"},
    {0x43db94, {0xbd469400, 0xd65f03c0}, 2, true, "getSwimWalkMaxSpeed"},
};

}  // namespace moonrush::offsets
