"""Generate game/src/offsets.hpp from the real SMO 1.0.0 code.

Every PlayerConst field offset is read from its getter (`ldr s0, [x0, #imm]; ret`), so nothing
is guessed from headers. Re-run after changing GROUPS.
"""
import os, struct, smo_disasm as s

GROUPS = {
    'walk': ['NormalMinSpeed', 'NormalMaxSpeed', 'RunAfterTurnSpeedMax', 'DashJudgeSpeed'],
    'squat': ['SquatWalkSpeed'],
    'dive': ['HeadSlidingSpeed', 'HeadSlidingSpeedMin'],
    'roll': ['SlopeRollingSpeedStart', 'SlopeRollingSpeedBoost', 'SlopeRollingMaxSpeed', 'SlopeRollingReStartMaxAdd'],
    'long_jump': ['LongJumpInitSpeed', 'LongJumpSpeed', 'LongJumpSpeedMin'],
    'air': ['JumpBaseSpeedMax', 'JumpMoveSpeedMin', 'JumpMoveSpeedMax'],
    'swim': ['SwimSurfaceSpeedMaxH', 'SwimHighSpeedMaxH', 'SwimLowSpeedMaxH', 'SwimFloorSpeedMaxH', 'SwimWalkMaxSpeed'],
}
FUNCS = {
    'PlayerActorHakoniwa_movement': '_ZN19PlayerActorHakoniwa8movementEv',
    'GameDataFunction_getTotalShineNum': '_ZN16GameDataFunction16getTotalShineNumE22GameDataHolderAccessori',
    'GameDataFunction_getCurrentShineNum': '_ZN16GameDataFunction18getCurrentShineNumE22GameDataHolderAccessor',
    'al_getSceneObj': '_ZN2al11getSceneObjEPKNS_18IUseSceneObjHolderEi',
}

syms = s.symbols(); img = s.flat_image()

def field_offset(name):
    mangled = f'_ZNK11PlayerConst{3 + len(name)}get{name}Ev'
    off, size, _ = syms[mangled]
    ldr, ret = struct.unpack_from('<II', img, off)
    assert ret == 0xd65f03c0, f'{name}: getter is not a plain load'
    assert (ldr & 0xffc003ff) == 0xbd400000, f'{name}: not "ldr s0, [x0, #imm]" ({ldr:08x})'
    return ((ldr >> 10) & 0xfff) * 4, off

# Verified by hand from disassembly (see docs/RESEARCH.md):
#   PlayerActorHakoniwa::initPlayer @0x41b704: bl createMarioConst; str x0, [x19, #304]
#   GameDataHolderAccessor(IUseSceneObjHolder*) @0x5316ec: al::getSceneObj(holder, 18)
#   LiveActor -> IUseSceneObjHolder: add x1, x0, #0x20 (153 call sites)
out = ['// GENERATED by tools/gen_offsets.py from SMO 1.0.0 (build 3CA12DFAAF9C82DA064D1698DF79CDA1). Do not edit.',
       '#pragma once', '#include <cstddef>', '#include <cstdint>', '', 'namespace moonrush::offsets {', '',
       'constexpr const char* kBuildId = "3CA12DFAAF9C82DA064D1698DF79CDA1";', '',
       '// Offsets into the main module.']
for k, sym in FUNCS.items():
    out.append(f'constexpr uintptr_t {k} = 0x{syms[sym][0]:x};  // {sym}')
out += ['', '// Object layout (verified in disassembly).',
        'constexpr size_t PlayerActorHakoniwa_mConst = 0x130;',
        'constexpr size_t LiveActor_IUseSceneObjHolder = 0x20;',
        'constexpr int SceneObjId_GameDataHolder = 18;',
        'constexpr size_t PlayerConst_size = 0x9a8;', '',
        '// offset: field inside PlayerConst. getter: the 8-byte `ldr s0, [x0, #offset]; ret` function Moonrush hooks.',
        'struct Field { const char* name; uint16_t offset; uintptr_t getter; };', '']
for g, names in GROUPS.items():
    out.append(f'constexpr Field k_{g}[] = {{')
    for n in names:
        fo, go = field_offset(n)
        assert fo < 0x9a8
        out.append(f'    {{"{n}", 0x{fo:x}, 0x{go:x}}},')
    out.append('};')
# Flat list of every getter, tagged with its group index (same order as moonrush::Group).
out += ['', 'struct Getter { int group; const char* name; uint16_t field; uintptr_t offset; };', 'constexpr Getter k_getters[] = {']
for gi, (g, names) in enumerate(GROUPS.items()):
    for n in names:
        fo, go = field_offset(n)
        out.append(f'    {{{gi}, "{n}", 0x{fo:x}, 0x{go:x}}},  // {g}')
out.append('};')

# Signatures: exact instruction words at every address Moonrush depends on. Checked at startup.
# Getters may instead start with a `b` (another mod hooked them first); Moonrush then stacks on top.
# Any other mismatch (other game version, or a patch Moonrush can't chain) means it stays inactive.
sigs = []
for k, sym in FUNCS.items():
    o = syms[sym][0]
    sigs.append((o, struct.unpack_from('<4I', img, o), k, False))
for g, names in GROUPS.items():
    for n in names:
        _, go = field_offset(n)
        sigs.append((go, struct.unpack_from('<2I', img, go) + (None, None), 'get' + n, True))
out += ['', 'struct Signature { uintptr_t offset; uint32_t words[4]; uint8_t count; bool hookable; const char* what; };',
        'constexpr Signature k_signatures[] = {']
for o, words, what, hookable in sigs:
    ws = [w for w in words if w is not None]
    out.append(f'    {{0x{o:x}, {{{", ".join(f"0x{w:08x}" for w in ws)}}}, {len(ws)}, {"true" if hookable else "false"}, "{what}"}},')
out.append('};')
out += ['', '}  // namespace moonrush::offsets', '']
dst = os.path.join(os.path.dirname(__file__), '..', 'game', 'source', 'moonrush', 'offsets.hpp')
os.makedirs(os.path.dirname(dst), exist_ok=True)
open(dst, 'w', encoding='utf-8', newline='\n').write('\n'.join(out))
print('\n'.join(out))
